[platformio]
default_envs = portenta_c33

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D CORE_DEBUG_LEVEL=3
lib_deps =
  h2zero/NimBLE-Arduino@^1.4.1

[env:portenta_c33]
platform = renesas-ra
board = portenta_c33
framework = arduino
monitor_speed = 115200
extra_scripts =
  pre:scripts/portenta_include_fix.py
lib_deps =
  arduino-libraries/ArduinoBLE@^1.4.1